Create Documentation
flagbit/category-bundle pull request #11
Opened 2022-03-09 10:38 UTC by flagbird

https://flagbit.github.io/category-bundle is currently linked to the documentation branch. It will be changed to tge main branch once it's merged.

2022-03-10 15:04 UTC, pascal-zarrad requested changes

2022-03-10 15:04 UTC, pascal-zarrad commented on docs/index.md
> +many more to enhance your categories with the data your shop needs. You can also localize the each category property for your
```suggestion
many more to enhance your categories with the data your shop needs. You can also localize each category property for your
```
I think the `the` does not belong there.

2022-03-10 15:04 UTC, pascal-zarrad commented on docs/index.md
> +Enable the bundle in the kernel:
Maybe we can leave out this sentence as done under "Import the routing" as it looks weird in the documentation. Also the code example already contains all necessary information (file path, code to paste)

2022-03-10 15:04 UTC, pascal-zarrad commented on docs/custom-types.md
> +that can be used in your project without contributing to the Bundle.
Maybe we should rephrase this a bit, as the first sentence is hard to read.

Maybe something like?
```suggestion
While the Category Bundle comes with many build-in property types, your project might need one that is very specific to your use case. Adding such a specific type to the official bundle might not make sense. Don't worry, the bundle allows you to create your own property type that can be used in your project without contributing to the Bundle.
```

2022-03-10 15:04 UTC, pascal-zarrad commented on docs/custom-types.md
> +occur when you do changes in your custom property on the category page. You can also access:
This sentence is also really complex, consider rephrasing it.

2022-03-11 12:57 UTC, flagbird commented on docs/index.md
> +Enable the bundle in the kernel:
Removed.

2022-03-11 13:00 UTC, flagbird commented on docs/custom-types.md
> +occur when you do changes in your custom property on the category page. You can also access:
@pascal-zarrad What do you think about:

```suggestion
The implemented `render()` method will get an instance of `PropertyDto` injected. The `PropertyDto` contains a method to 
apply changes from your custom property on the category page. You can also access:
```

2022-03-11 13:17 UTC, pascal-zarrad commented on docs/custom-types.md
> +occur when you do changes in your custom property on the category page. You can also access:
@flagbird this would be fine 👍🏻

2022-03-11 13:21 UTC, pascal-zarrad approved these changes
LGTM 👍

2022-03-11 13:23 UTC, merged